/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AanmeldenRouteImport } from './routes/aanmelden'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BedrijvenRouteImport } from './routes/bedrijven'
import { Route as InloggenRouteImport } from './routes/inloggen'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as VerhurenRouteImport } from './routes/verhuren'
import { Route as WachtwoordVergetenRouteImport } from './routes/wachtwoord-vergeten'
import { Route as AfrekenenIdRouteImport } from './routes/afrekenen.$id'
import { Route as JurkenIndexRouteImport } from './routes/jurken.index'
import { Route as JurkenIdRouteImport } from './routes/jurken.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AanmeldenRoute = AanmeldenRouteImport.update({
  id: '/aanmelden',
  path: '/aanmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BedrijvenRoute = BedrijvenRouteImport.update({
  id: '/bedrijven',
  path: '/bedrijven',
  getParentRoute: () => rootRouteImport,
} as any)
const InloggenRoute = InloggenRouteImport.update({
  id: '/inloggen',
  path: '/inloggen',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const VerhurenRoute = VerhurenRouteImport.update({
  id: '/verhuren',
  path: '/verhuren',
  getParentRoute: () => rootRouteImport,
} as any)
const WachtwoordVergetenRoute = WachtwoordVergetenRouteImport.update({
  id: '/wachtwoord-vergeten',
  path: '/wachtwoord-vergeten',
  getParentRoute: () => rootRouteImport,
} as any)
const AfrekenenIdRoute = AfrekenenIdRouteImport.update({
  id: '/afrekenen/$id',
  path: '/afrekenen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JurkenIndexRoute = JurkenIndexRouteImport.update({
  id: '/jurken/',
  path: '/jurken/',
  getParentRoute: () => rootRouteImport,
} as any)
const JurkenIdRoute = JurkenIdRouteImport.update({
  id: '/jurken/$id',
  path: '/jurken/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/account': typeof AccountRoute
  '/bedrijven': typeof BedrijvenRoute
  '/inloggen': typeof InloggenRoute
  '/over-ons': typeof OverOnsRoute
  '/verhuren': typeof VerhurenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/jurken/': typeof JurkenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/account': typeof AccountRoute
  '/bedrijven': typeof BedrijvenRoute
  '/inloggen': typeof InloggenRoute
  '/over-ons': typeof OverOnsRoute
  '/verhuren': typeof VerhurenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/jurken': typeof JurkenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/account': typeof AccountRoute
  '/bedrijven': typeof BedrijvenRoute
  '/inloggen': typeof InloggenRoute
  '/over-ons': typeof OverOnsRoute
  '/verhuren': typeof VerhurenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/jurken/': typeof JurkenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanmelden'
    | '/account'
    | '/bedrijven'
    | '/inloggen'
    | '/over-ons'
    | '/verhuren'
    | '/wachtwoord-vergeten'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/jurken/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aanmelden'
    | '/account'
    | '/bedrijven'
    | '/inloggen'
    | '/over-ons'
    | '/verhuren'
    | '/wachtwoord-vergeten'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/jurken'
  id:
    | '__root__'
    | '/'
    | '/aanmelden'
    | '/account'
    | '/bedrijven'
    | '/inloggen'
    | '/over-ons'
    | '/verhuren'
    | '/wachtwoord-vergeten'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/jurken/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanmeldenRoute: typeof AanmeldenRoute
  AccountRoute: typeof AccountRoute
  BedrijvenRoute: typeof BedrijvenRoute
  InloggenRoute: typeof InloggenRoute
  OverOnsRoute: typeof OverOnsRoute
  VerhurenRoute: typeof VerhurenRoute
  WachtwoordVergetenRoute: typeof WachtwoordVergetenRoute
  AfrekenenIdRoute: typeof AfrekenenIdRoute
  JurkenIdRoute: typeof JurkenIdRoute
  JurkenIndexRoute: typeof JurkenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanmelden': {
      id: '/aanmelden'
      path: '/aanmelden'
      fullPath: '/aanmelden'
      preLoaderRoute: typeof AanmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrijven': {
      id: '/bedrijven'
      path: '/bedrijven'
      fullPath: '/bedrijven'
      preLoaderRoute: typeof BedrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inloggen': {
      id: '/inloggen'
      path: '/inloggen'
      fullPath: '/inloggen'
      preLoaderRoute: typeof InloggenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verhuren': {
      id: '/verhuren'
      path: '/verhuren'
      fullPath: '/verhuren'
      preLoaderRoute: typeof VerhurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wachtwoord-vergeten': {
      id: '/wachtwoord-vergeten'
      path: '/wachtwoord-vergeten'
      fullPath: '/wachtwoord-vergeten'
      preLoaderRoute: typeof WachtwoordVergetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afrekenen/$id': {
      id: '/afrekenen/$id'
      path: '/afrekenen/$id'
      fullPath: '/afrekenen/$id'
      preLoaderRoute: typeof AfrekenenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurken/': {
      id: '/jurken/'
      path: '/jurken'
      fullPath: '/jurken/'
      preLoaderRoute: typeof JurkenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurken/$id': {
      id: '/jurken/$id'
      path: '/jurken/$id'
      fullPath: '/jurken/$id'
      preLoaderRoute: typeof JurkenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanmeldenRoute: AanmeldenRoute,
  AccountRoute: AccountRoute,
  BedrijvenRoute: BedrijvenRoute,
  InloggenRoute: InloggenRoute,
  OverOnsRoute: OverOnsRoute,
  VerhurenRoute: VerhurenRoute,
  WachtwoordVergetenRoute: WachtwoordVergetenRoute,
  AfrekenenIdRoute: AfrekenenIdRoute,
  JurkenIdRoute: JurkenIdRoute,
  JurkenIndexRoute: JurkenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
