/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AanmeldenRouteImport } from './routes/aanmelden'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BedrijvenRouteImport } from './routes/bedrijven'
import { Route as InloggenRouteImport } from './routes/inloggen'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as VeelgesteldeVragenRouteImport } from './routes/veelgestelde-vragen'
import { Route as VerhurenRouteImport } from './routes/verhuren'
import { Route as WachtwoordVergetenRouteImport } from './routes/wachtwoord-vergeten'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountBerichtenRouteImport } from './routes/account.berichten'
import { Route as AccountFavorietenRouteImport } from './routes/account.favorieten'
import { Route as AccountHuuritemsRouteImport } from './routes/account.huuritems'
import { Route as AccountInstellingenRouteImport } from './routes/account.instellingen'
import { Route as AccountMeldingenRouteImport } from './routes/account.meldingen'
import { Route as AccountProfielRouteImport } from './routes/account.profiel'
import { Route as AccountVerhuurRouteImport } from './routes/account.verhuur'
import { Route as AfrekenenIdRouteImport } from './routes/afrekenen.$id'
import { Route as JurkenIndexRouteImport } from './routes/jurken.index'
import { Route as JurkenIdRouteImport } from './routes/jurken.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AanmeldenRoute = AanmeldenRouteImport.update({
  id: '/aanmelden',
  path: '/aanmelden',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BedrijvenRoute = BedrijvenRouteImport.update({
  id: '/bedrijven',
  path: '/bedrijven',
  getParentRoute: () => rootRouteImport,
} as any)
const InloggenRoute = InloggenRouteImport.update({
  id: '/inloggen',
  path: '/inloggen',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const VeelgesteldeVragenRoute = VeelgesteldeVragenRouteImport.update({
  id: '/veelgestelde-vragen',
  path: '/veelgestelde-vragen',
  getParentRoute: () => rootRouteImport,
} as any)
const VerhurenRoute = VerhurenRouteImport.update({
  id: '/verhuren',
  path: '/verhuren',
  getParentRoute: () => rootRouteImport,
} as any)
const WachtwoordVergetenRoute = WachtwoordVergetenRouteImport.update({
  id: '/wachtwoord-vergeten',
  path: '/wachtwoord-vergeten',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBerichtenRoute = AccountBerichtenRouteImport.update({
  id: '/berichten',
  path: '/berichten',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavorietenRoute = AccountFavorietenRouteImport.update({
  id: '/favorieten',
  path: '/favorieten',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHuuritemsRoute = AccountHuuritemsRouteImport.update({
  id: '/huuritems',
  path: '/huuritems',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInstellingenRoute = AccountInstellingenRouteImport.update({
  id: '/instellingen',
  path: '/instellingen',
  getParentRoute: () => AccountRoute,
} as any)
const AccountMeldingenRoute = AccountMeldingenRouteImport.update({
  id: '/meldingen',
  path: '/meldingen',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfielRoute = AccountProfielRouteImport.update({
  id: '/profiel',
  path: '/profiel',
  getParentRoute: () => AccountRoute,
} as any)
const AccountVerhuurRoute = AccountVerhuurRouteImport.update({
  id: '/verhuur',
  path: '/verhuur',
  getParentRoute: () => AccountRoute,
} as any)
const AfrekenenIdRoute = AfrekenenIdRouteImport.update({
  id: '/afrekenen/$id',
  path: '/afrekenen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JurkenIndexRoute = JurkenIndexRouteImport.update({
  id: '/jurken/',
  path: '/jurken/',
  getParentRoute: () => rootRouteImport,
} as any)
const JurkenIdRoute = JurkenIdRouteImport.update({
  id: '/jurken/$id',
  path: '/jurken/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/account': typeof AccountRouteWithChildren
  '/bedrijven': typeof BedrijvenRoute
  '/inloggen': typeof InloggenRoute
  '/over-ons': typeof OverOnsRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/verhuren': typeof VerhurenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/account/berichten': typeof AccountBerichtenRoute
  '/account/favorieten': typeof AccountFavorietenRoute
  '/account/huuritems': typeof AccountHuuritemsRoute
  '/account/instellingen': typeof AccountInstellingenRoute
  '/account/meldingen': typeof AccountMeldingenRoute
  '/account/profiel': typeof AccountProfielRoute
  '/account/verhuur': typeof AccountVerhuurRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/account/': typeof AccountIndexRoute
  '/jurken/': typeof JurkenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/bedrijven': typeof BedrijvenRoute
  '/inloggen': typeof InloggenRoute
  '/over-ons': typeof OverOnsRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/verhuren': typeof VerhurenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/account/berichten': typeof AccountBerichtenRoute
  '/account/favorieten': typeof AccountFavorietenRoute
  '/account/huuritems': typeof AccountHuuritemsRoute
  '/account/instellingen': typeof AccountInstellingenRoute
  '/account/meldingen': typeof AccountMeldingenRoute
  '/account/profiel': typeof AccountProfielRoute
  '/account/verhuur': typeof AccountVerhuurRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/account': typeof AccountIndexRoute
  '/jurken': typeof JurkenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aanmelden': typeof AanmeldenRoute
  '/account': typeof AccountRouteWithChildren
  '/bedrijven': typeof BedrijvenRoute
  '/inloggen': typeof InloggenRoute
  '/over-ons': typeof OverOnsRoute
  '/veelgestelde-vragen': typeof VeelgesteldeVragenRoute
  '/verhuren': typeof VerhurenRoute
  '/wachtwoord-vergeten': typeof WachtwoordVergetenRoute
  '/account/berichten': typeof AccountBerichtenRoute
  '/account/favorieten': typeof AccountFavorietenRoute
  '/account/huuritems': typeof AccountHuuritemsRoute
  '/account/instellingen': typeof AccountInstellingenRoute
  '/account/meldingen': typeof AccountMeldingenRoute
  '/account/profiel': typeof AccountProfielRoute
  '/account/verhuur': typeof AccountVerhuurRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/account/': typeof AccountIndexRoute
  '/jurken/': typeof JurkenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aanmelden'
    | '/account'
    | '/bedrijven'
    | '/inloggen'
    | '/over-ons'
    | '/veelgestelde-vragen'
    | '/verhuren'
    | '/wachtwoord-vergeten'
    | '/account/berichten'
    | '/account/favorieten'
    | '/account/huuritems'
    | '/account/instellingen'
    | '/account/meldingen'
    | '/account/profiel'
    | '/account/verhuur'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/account/'
    | '/jurken/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aanmelden'
    | '/bedrijven'
    | '/inloggen'
    | '/over-ons'
    | '/veelgestelde-vragen'
    | '/verhuren'
    | '/wachtwoord-vergeten'
    | '/account/berichten'
    | '/account/favorieten'
    | '/account/huuritems'
    | '/account/instellingen'
    | '/account/meldingen'
    | '/account/profiel'
    | '/account/verhuur'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/account'
    | '/jurken'
  id:
    | '__root__'
    | '/'
    | '/aanmelden'
    | '/account'
    | '/bedrijven'
    | '/inloggen'
    | '/over-ons'
    | '/veelgestelde-vragen'
    | '/verhuren'
    | '/wachtwoord-vergeten'
    | '/account/berichten'
    | '/account/favorieten'
    | '/account/huuritems'
    | '/account/instellingen'
    | '/account/meldingen'
    | '/account/profiel'
    | '/account/verhuur'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/account/'
    | '/jurken/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AanmeldenRoute: typeof AanmeldenRoute
  AccountRoute: typeof AccountRouteWithChildren
  BedrijvenRoute: typeof BedrijvenRoute
  InloggenRoute: typeof InloggenRoute
  OverOnsRoute: typeof OverOnsRoute
  VeelgesteldeVragenRoute: typeof VeelgesteldeVragenRoute
  VerhurenRoute: typeof VerhurenRoute
  WachtwoordVergetenRoute: typeof WachtwoordVergetenRoute
  AfrekenenIdRoute: typeof AfrekenenIdRoute
  JurkenIdRoute: typeof JurkenIdRoute
  JurkenIndexRoute: typeof JurkenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aanmelden': {
      id: '/aanmelden'
      path: '/aanmelden'
      fullPath: '/aanmelden'
      preLoaderRoute: typeof AanmeldenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrijven': {
      id: '/bedrijven'
      path: '/bedrijven'
      fullPath: '/bedrijven'
      preLoaderRoute: typeof BedrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inloggen': {
      id: '/inloggen'
      path: '/inloggen'
      fullPath: '/inloggen'
      preLoaderRoute: typeof InloggenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veelgestelde-vragen': {
      id: '/veelgestelde-vragen'
      path: '/veelgestelde-vragen'
      fullPath: '/veelgestelde-vragen'
      preLoaderRoute: typeof VeelgesteldeVragenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verhuren': {
      id: '/verhuren'
      path: '/verhuren'
      fullPath: '/verhuren'
      preLoaderRoute: typeof VerhurenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wachtwoord-vergeten': {
      id: '/wachtwoord-vergeten'
      path: '/wachtwoord-vergeten'
      fullPath: '/wachtwoord-vergeten'
      preLoaderRoute: typeof WachtwoordVergetenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/berichten': {
      id: '/account/berichten'
      path: '/berichten'
      fullPath: '/account/berichten'
      preLoaderRoute: typeof AccountBerichtenRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favorieten': {
      id: '/account/favorieten'
      path: '/favorieten'
      fullPath: '/account/favorieten'
      preLoaderRoute: typeof AccountFavorietenRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/huuritems': {
      id: '/account/huuritems'
      path: '/huuritems'
      fullPath: '/account/huuritems'
      preLoaderRoute: typeof AccountHuuritemsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/instellingen': {
      id: '/account/instellingen'
      path: '/instellingen'
      fullPath: '/account/instellingen'
      preLoaderRoute: typeof AccountInstellingenRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/meldingen': {
      id: '/account/meldingen'
      path: '/meldingen'
      fullPath: '/account/meldingen'
      preLoaderRoute: typeof AccountMeldingenRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profiel': {
      id: '/account/profiel'
      path: '/profiel'
      fullPath: '/account/profiel'
      preLoaderRoute: typeof AccountProfielRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/verhuur': {
      id: '/account/verhuur'
      path: '/verhuur'
      fullPath: '/account/verhuur'
      preLoaderRoute: typeof AccountVerhuurRouteImport
      parentRoute: typeof AccountRoute
    }
    '/afrekenen/$id': {
      id: '/afrekenen/$id'
      path: '/afrekenen/$id'
      fullPath: '/afrekenen/$id'
      preLoaderRoute: typeof AfrekenenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurken/': {
      id: '/jurken/'
      path: '/jurken'
      fullPath: '/jurken/'
      preLoaderRoute: typeof JurkenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurken/$id': {
      id: '/jurken/$id'
      path: '/jurken/$id'
      fullPath: '/jurken/$id'
      preLoaderRoute: typeof JurkenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountBerichtenRoute: typeof AccountBerichtenRoute
  AccountFavorietenRoute: typeof AccountFavorietenRoute
  AccountHuuritemsRoute: typeof AccountHuuritemsRoute
  AccountInstellingenRoute: typeof AccountInstellingenRoute
  AccountMeldingenRoute: typeof AccountMeldingenRoute
  AccountProfielRoute: typeof AccountProfielRoute
  AccountVerhuurRoute: typeof AccountVerhuurRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBerichtenRoute: AccountBerichtenRoute,
  AccountFavorietenRoute: AccountFavorietenRoute,
  AccountHuuritemsRoute: AccountHuuritemsRoute,
  AccountInstellingenRoute: AccountInstellingenRoute,
  AccountMeldingenRoute: AccountMeldingenRoute,
  AccountProfielRoute: AccountProfielRoute,
  AccountVerhuurRoute: AccountVerhuurRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AanmeldenRoute: AanmeldenRoute,
  AccountRoute: AccountRouteWithChildren,
  BedrijvenRoute: BedrijvenRoute,
  InloggenRoute: InloggenRoute,
  OverOnsRoute: OverOnsRoute,
  VeelgesteldeVragenRoute: VeelgesteldeVragenRoute,
  VerhurenRoute: VerhurenRoute,
  WachtwoordVergetenRoute: WachtwoordVergetenRoute,
  AfrekenenIdRoute: AfrekenenIdRoute,
  JurkenIdRoute: JurkenIdRoute,
  JurkenIndexRoute: JurkenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
