/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BedrijvenRouteImport } from './routes/bedrijven'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as AfrekenenIdRouteImport } from './routes/afrekenen.$id'
import { Route as JurkenIndexRouteImport } from './routes/jurken.index'
import { Route as JurkenIdRouteImport } from './routes/jurken.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BedrijvenRoute = BedrijvenRouteImport.update({
  id: '/bedrijven',
  path: '/bedrijven',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const AfrekenenIdRoute = AfrekenenIdRouteImport.update({
  id: '/afrekenen/$id',
  path: '/afrekenen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JurkenIndexRoute = JurkenIndexRouteImport.update({
  id: '/jurken/',
  path: '/jurken/',
  getParentRoute: () => rootRouteImport,
} as any)
const JurkenIdRoute = JurkenIdRouteImport.update({
  id: '/jurken/$id',
  path: '/jurken/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bedrijven': typeof BedrijvenRoute
  '/over-ons': typeof OverOnsRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/jurken/': typeof JurkenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bedrijven': typeof BedrijvenRoute
  '/over-ons': typeof OverOnsRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/jurken': typeof JurkenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bedrijven': typeof BedrijvenRoute
  '/over-ons': typeof OverOnsRoute
  '/afrekenen/$id': typeof AfrekenenIdRoute
  '/jurken/$id': typeof JurkenIdRoute
  '/jurken/': typeof JurkenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bedrijven'
    | '/over-ons'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/jurken/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bedrijven'
    | '/over-ons'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/jurken'
  id:
    | '__root__'
    | '/'
    | '/bedrijven'
    | '/over-ons'
    | '/afrekenen/$id'
    | '/jurken/$id'
    | '/jurken/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BedrijvenRoute: typeof BedrijvenRoute
  OverOnsRoute: typeof OverOnsRoute
  AfrekenenIdRoute: typeof AfrekenenIdRoute
  JurkenIdRoute: typeof JurkenIdRoute
  JurkenIndexRoute: typeof JurkenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedrijven': {
      id: '/bedrijven'
      path: '/bedrijven'
      fullPath: '/bedrijven'
      preLoaderRoute: typeof BedrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afrekenen/$id': {
      id: '/afrekenen/$id'
      path: '/afrekenen/$id'
      fullPath: '/afrekenen/$id'
      preLoaderRoute: typeof AfrekenenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurken/': {
      id: '/jurken/'
      path: '/jurken'
      fullPath: '/jurken/'
      preLoaderRoute: typeof JurkenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jurken/$id': {
      id: '/jurken/$id'
      path: '/jurken/$id'
      fullPath: '/jurken/$id'
      preLoaderRoute: typeof JurkenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BedrijvenRoute: BedrijvenRoute,
  OverOnsRoute: OverOnsRoute,
  AfrekenenIdRoute: AfrekenenIdRoute,
  JurkenIdRoute: JurkenIdRoute,
  JurkenIndexRoute: JurkenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
